server {
    listen       81;
    server_name  117.72.189.56; # 修改为docker服务宿主机的ip
    
    # 添加gzip相关配置
    gzip on;
    gzip_static on;  # 启用gzip_static模块，支持预压缩的.gz文件
    gzip_comp_level 5;
    gzip_types text/plain text/css application/javascript application/json text/xml application/xml application/xml+rss text/javascript image/svg+xml;
    gzip_vary on;  # 添加Vary: Accept-Encoding响应头
    gzip_proxied any;  # 为代理请求启用gzip
    gzip_disable "msie6";  # 为IE6及以下版本禁用gzip
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
    
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}